# Generated by Django 2.0.4 on 2018-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.BooleanField(default=True),
        ),
    ]
