# Generated by Django 2.0.4 on 2018-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0002_course_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_type',
            new_name='obligative',
        ),
    ]
