# Generated by Django 2.0.4 on 2018-06-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0003_auto_20180613_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provimetmundshme',
            name='course',
        ),
        migrations.RemoveField(
            model_name='provimetmundshme',
            name='program',
        ),
        migrations.RemoveField(
            model_name='registeredcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registeredcourse',
            name='program',
        ),
        migrations.RemoveField(
            model_name='registeredcourse',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Master')], default='Bachelor', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
        migrations.DeleteModel(
            name='ProvimetMundshme',
        ),
        migrations.DeleteModel(
            name='RegisteredCourse',
        ),
    ]
