# Generated by Django 2.0.4 on 2018-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0003_auto_20180506_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='credits',
        ),
        migrations.AddField(
            model_name='program',
            name='summary',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
