# Generated by Django 2.0.4 on 2018-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0005_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], default='Bachelor', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='course', to='sems.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_teacher',
            field=models.ManyToManyField(blank=True, related_name='course_teacher', to='sems.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], default=1, max_length=100),
        ),
    ]
