# Generated by Django 2.0.4 on 2018-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0006_auto_20180614_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='afatet_provimeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muaji', models.IntegerField(choices=[(1, 'Janar'), (2, 'Shkurt'), (3, 'Mars'), (4, 'Prill'), (5, 'Maj'), (6, 'Qershor'), (7, 'Korrik'), (8, 'Gusht'), (9, 'Shtator'), (10, 'Tetor'), (11, 'Nentor'), (12, 'Dhjetor')], default=1)),
                ('prej', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('deri', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('mundesite', models.IntegerField(default=3, null=True)),
            ],
        ),
    ]
