# Generated by Django 2.0.4 on 2018-05-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0006_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
