# Generated by Django 2.0.4 on 2018-05-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0007_auto_20180506_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
