# Generated by Django 2.0.4 on 2018-06-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0008_auto_20180616_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afatet_provimeve',
            name='mundesite',
        ),
    ]
