# Generated by Django 2.0.4 on 2018-06-18 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sems', '0010_afatet_provimeve_emri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provimet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('times', models.IntegerField(default=0)),
                ('course', models.ManyToManyField(to='sems.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
