# Generated by Django 2.0.4 on 2018-05-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0010_uploaded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploaded',
            new_name='Upload',
        ),
    ]
