# Generated by Django 2.0.4 on 2018-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0013_auto_20180618_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='provimet',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
