# Generated by Django 2.0.4 on 2018-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0014_provimet_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='provimet',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ne progres'), (1, 'Aprovuar'), (2, 'Refuzuar')], default=0),
        ),
    ]
