# Generated by Django 2.0.4 on 2018-06-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0016_remove_provimet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afatet_provimeve',
            name='deri',
        ),
        migrations.RemoveField(
            model_name='afatet_provimeve',
            name='prej',
        ),
        migrations.AddField(
            model_name='afatet_provimeve',
            name='aktiv',
            field=models.BooleanField(default=False),
        ),
    ]
