# Generated by Django 2.0.4 on 2018-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0017_auto_20180509_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
