# Generated by Django 2.0.4 on 2018-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0020_auto_20180509_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
