# Generated by Django 2.0.4 on 2018-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0022_auto_20180509_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='no-img.png', null=True, upload_to=''),
        ),
    ]
