# Generated by Django 2.0.4 on 2018-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems', '0023_auto_20180509_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='no-img.png', null=True, upload_to=''),
        ),
    ]
